//go:build ignore

package main

import (
	"os"
	"text/template"
)

var uuidTypes = []struct {
	Type   string // e.g. "AgentID"
	Entity string // e.g. "agent"
}{
	{"AgentID", "agent"},
	{"ApprovalID", "approval"},
	{"ServiceID", "service"},
	{"GrantID", "grant"},
	{"SessionID", "session"},
	{"RefreshSessionID", "refresh session"},
	{"UserID", "user"},
	{"PermissionSetID", "permission_set"},
	{"CredentialID", "broker client credential"},
	{"SigningKeyID", "signing key"},
	{"AuthorizationCodeID", "authorization code"},
}

var tmpl = template.Must(template.New("ids").Parse(`// Code generated by gen_ids.go; DO NOT EDIT.
package id

import (
	"database/sql/driver"
	"encoding/json"

	"github.com/google/uuid"
)
{{range .}}
// {{.Type}} uniquely identifies a {{.Entity}} entity.
type {{.Type}} uuid.UUID

func New{{.Type}}() {{.Type}}                        { return {{.Type}}(uuid.New()) }
func Parse{{.Type}}(s string) ({{.Type}}, error)     { id, err := uuid.Parse(s); return {{.Type}}(id), err }
func MustParse{{.Type}}(s string) {{.Type}}          { return {{.Type}}(uuid.MustParse(s)) }
func (id {{.Type}}) String() string                  { return uuid.UUID(id).String() }
func (id {{.Type}}) IsZero() bool                    { return uuid.UUID(id) == uuid.Nil }
func (id {{.Type}}) MarshalJSON() ([]byte, error)    { return json.Marshal(uuid.UUID(id).String()) }
func (id *{{.Type}}) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = {{.Type}}(parsed)
	return nil
}
func (id {{.Type}}) Value() (driver.Value, error)    { return uuid.UUID(id).String(), nil }
func (id *{{.Type}}) Scan(src interface{}) error      { return (*uuid.UUID)(id).Scan(src) }
func (id {{.Type}}) MarshalText() ([]byte, error)    { return uuid.UUID(id).MarshalText() }
func (id *{{.Type}}) UnmarshalText(b []byte) error   { return (*uuid.UUID)(id).UnmarshalText(b) }
{{end}}`))

func main() {
	f, err := os.Create("uuid_ids_gen.go")
	if err != nil {
		panic(err)
	}
	defer f.Close()
	if err := tmpl.Execute(f, uuidTypes); err != nil {
		panic(err)
	}
}
