// Code generated by gen_ids.go; DO NOT EDIT.
package id

import (
	"database/sql/driver"
	"encoding/json"

	"github.com/google/uuid"
)

// AgentID uniquely identifies a agent entity.
type AgentID uuid.UUID

func NewAgentID() AgentID                       { return AgentID(uuid.New()) }
func ParseAgentID(s string) (AgentID, error)    { id, err := uuid.Parse(s); return AgentID(id), err }
func MustParseAgentID(s string) AgentID         { return AgentID(uuid.MustParse(s)) }
func (id AgentID) String() string               { return uuid.UUID(id).String() }
func (id AgentID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id AgentID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *AgentID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = AgentID(parsed)
	return nil
}
func (id AgentID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *AgentID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id AgentID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *AgentID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// ApprovalID uniquely identifies a approval entity.
type ApprovalID uuid.UUID

func NewApprovalID() ApprovalID { return ApprovalID(uuid.New()) }
func ParseApprovalID(s string) (ApprovalID, error) {
	id, err := uuid.Parse(s)
	return ApprovalID(id), err
}
func MustParseApprovalID(s string) ApprovalID      { return ApprovalID(uuid.MustParse(s)) }
func (id ApprovalID) String() string               { return uuid.UUID(id).String() }
func (id ApprovalID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id ApprovalID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *ApprovalID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = ApprovalID(parsed)
	return nil
}
func (id ApprovalID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *ApprovalID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id ApprovalID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *ApprovalID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// BusinessEventID uniquely identifies a business event entity.
type BusinessEventID uuid.UUID

func NewBusinessEventID() BusinessEventID { return BusinessEventID(uuid.New()) }
func ParseBusinessEventID(s string) (BusinessEventID, error) {
	id, err := uuid.Parse(s)
	return BusinessEventID(id), err
}
func MustParseBusinessEventID(s string) BusinessEventID { return BusinessEventID(uuid.MustParse(s)) }
func (id BusinessEventID) String() string               { return uuid.UUID(id).String() }
func (id BusinessEventID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id BusinessEventID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *BusinessEventID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = BusinessEventID(parsed)
	return nil
}
func (id BusinessEventID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *BusinessEventID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id BusinessEventID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *BusinessEventID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// ServiceID uniquely identifies a service entity.
type ServiceID uuid.UUID

func NewServiceID() ServiceID                     { return ServiceID(uuid.New()) }
func ParseServiceID(s string) (ServiceID, error)  { id, err := uuid.Parse(s); return ServiceID(id), err }
func MustParseServiceID(s string) ServiceID       { return ServiceID(uuid.MustParse(s)) }
func (id ServiceID) String() string               { return uuid.UUID(id).String() }
func (id ServiceID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id ServiceID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *ServiceID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = ServiceID(parsed)
	return nil
}
func (id ServiceID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *ServiceID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id ServiceID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *ServiceID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// GrantID uniquely identifies a grant entity.
type GrantID uuid.UUID

func NewGrantID() GrantID                       { return GrantID(uuid.New()) }
func ParseGrantID(s string) (GrantID, error)    { id, err := uuid.Parse(s); return GrantID(id), err }
func MustParseGrantID(s string) GrantID         { return GrantID(uuid.MustParse(s)) }
func (id GrantID) String() string               { return uuid.UUID(id).String() }
func (id GrantID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id GrantID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *GrantID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = GrantID(parsed)
	return nil
}
func (id GrantID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *GrantID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id GrantID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *GrantID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// SessionID uniquely identifies a session entity.
type SessionID uuid.UUID

func NewSessionID() SessionID                     { return SessionID(uuid.New()) }
func ParseSessionID(s string) (SessionID, error)  { id, err := uuid.Parse(s); return SessionID(id), err }
func MustParseSessionID(s string) SessionID       { return SessionID(uuid.MustParse(s)) }
func (id SessionID) String() string               { return uuid.UUID(id).String() }
func (id SessionID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id SessionID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *SessionID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = SessionID(parsed)
	return nil
}
func (id SessionID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *SessionID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id SessionID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *SessionID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// UserID uniquely identifies a user entity.
type UserID uuid.UUID

func NewUserID() UserID                        { return UserID(uuid.New()) }
func ParseUserID(s string) (UserID, error)     { id, err := uuid.Parse(s); return UserID(id), err }
func MustParseUserID(s string) UserID          { return UserID(uuid.MustParse(s)) }
func (id UserID) String() string               { return uuid.UUID(id).String() }
func (id UserID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id UserID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *UserID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = UserID(parsed)
	return nil
}
func (id UserID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *UserID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id UserID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *UserID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// PermissionSetID uniquely identifies a permission_set entity.
type PermissionSetID uuid.UUID

func NewPermissionSetID() PermissionSetID { return PermissionSetID(uuid.New()) }
func ParsePermissionSetID(s string) (PermissionSetID, error) {
	id, err := uuid.Parse(s)
	return PermissionSetID(id), err
}
func MustParsePermissionSetID(s string) PermissionSetID { return PermissionSetID(uuid.MustParse(s)) }
func (id PermissionSetID) String() string               { return uuid.UUID(id).String() }
func (id PermissionSetID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id PermissionSetID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *PermissionSetID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = PermissionSetID(parsed)
	return nil
}
func (id PermissionSetID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *PermissionSetID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id PermissionSetID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *PermissionSetID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// CredentialID uniquely identifies a broker client credential entity.
type CredentialID uuid.UUID

func NewCredentialID() CredentialID { return CredentialID(uuid.New()) }
func ParseCredentialID(s string) (CredentialID, error) {
	id, err := uuid.Parse(s)
	return CredentialID(id), err
}
func MustParseCredentialID(s string) CredentialID    { return CredentialID(uuid.MustParse(s)) }
func (id CredentialID) String() string               { return uuid.UUID(id).String() }
func (id CredentialID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id CredentialID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *CredentialID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = CredentialID(parsed)
	return nil
}
func (id CredentialID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *CredentialID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id CredentialID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *CredentialID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// SigningKeyID uniquely identifies a signing key entity.
type SigningKeyID uuid.UUID

func NewSigningKeyID() SigningKeyID { return SigningKeyID(uuid.New()) }
func ParseSigningKeyID(s string) (SigningKeyID, error) {
	id, err := uuid.Parse(s)
	return SigningKeyID(id), err
}
func MustParseSigningKeyID(s string) SigningKeyID    { return SigningKeyID(uuid.MustParse(s)) }
func (id SigningKeyID) String() string               { return uuid.UUID(id).String() }
func (id SigningKeyID) IsZero() bool                 { return uuid.UUID(id) == uuid.Nil }
func (id SigningKeyID) MarshalJSON() ([]byte, error) { return json.Marshal(uuid.UUID(id).String()) }
func (id *SigningKeyID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = SigningKeyID(parsed)
	return nil
}
func (id SigningKeyID) Value() (driver.Value, error)  { return uuid.UUID(id).String(), nil }
func (id *SigningKeyID) Scan(src interface{}) error   { return (*uuid.UUID)(id).Scan(src) }
func (id SigningKeyID) MarshalText() ([]byte, error)  { return uuid.UUID(id).MarshalText() }
func (id *SigningKeyID) UnmarshalText(b []byte) error { return (*uuid.UUID)(id).UnmarshalText(b) }

// AuthorizationCodeID uniquely identifies a authorization code entity.
type AuthorizationCodeID uuid.UUID

func NewAuthorizationCodeID() AuthorizationCodeID { return AuthorizationCodeID(uuid.New()) }
func ParseAuthorizationCodeID(s string) (AuthorizationCodeID, error) {
	id, err := uuid.Parse(s)
	return AuthorizationCodeID(id), err
}
func MustParseAuthorizationCodeID(s string) AuthorizationCodeID {
	return AuthorizationCodeID(uuid.MustParse(s))
}
func (id AuthorizationCodeID) String() string { return uuid.UUID(id).String() }
func (id AuthorizationCodeID) IsZero() bool   { return uuid.UUID(id) == uuid.Nil }
func (id AuthorizationCodeID) MarshalJSON() ([]byte, error) {
	return json.Marshal(uuid.UUID(id).String())
}
func (id *AuthorizationCodeID) UnmarshalJSON(b []byte) error {
	var s string
	if err := json.Unmarshal(b, &s); err != nil {
		return err
	}
	parsed, err := uuid.Parse(s)
	if err != nil {
		return err
	}
	*id = AuthorizationCodeID(parsed)
	return nil
}
func (id AuthorizationCodeID) Value() (driver.Value, error) { return uuid.UUID(id).String(), nil }
func (id *AuthorizationCodeID) Scan(src interface{}) error  { return (*uuid.UUID)(id).Scan(src) }
func (id AuthorizationCodeID) MarshalText() ([]byte, error) { return uuid.UUID(id).MarshalText() }
func (id *AuthorizationCodeID) UnmarshalText(b []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(b)
}
