export const approvalCopy = {
  title: 'Tool approval request',
  description: 'Review the tool call and its scope before you decide.',
  requestedBy: 'Requested by',
  requestedAt: (age: string) => `Requested ${age}`,
  decisionTimeUnknown: 'Decision time unavailable',
  actingUser: 'Acting user',
  action: 'Action',
  technicalDetails: 'Technical details',
  arguments: 'Arguments',
  moreArguments: (count: number) => `${count} more ${count === 1 ? 'argument' : 'arguments'} in JSON`,
  sessionContext: 'Session context',
  agentSession: 'Agent session',
  mcpSession: 'MCP session',
  toolInvocation: 'Tool invocation',
  covers: 'Covers',
  patternPreview: 'Approval pattern preview',
  expiry: (date: string) => `Expires: ${date}`,
  lowRisk: 'Low risk',
  mediumRisk: 'Medium risk',
  highRisk: 'High risk',
  criticalRisk: 'Critical risk',
  otherRisk: (level: string) => `${level} risk`,
  riskExplanation: 'The server supplies this risk rating. A low rating does not guarantee that the tool call is safe.',
  unratedExplanation: 'The server did not supply a risk rating for this tool call.',
  session: 'For this session',
  permanent: 'Always allow',
  permanentWarning: 'This grants permanent access. You can revoke it from Approvals.',
  rememberDescription: 'Review how long this decision lasts and the scope it covers. Only your confirmation records this approval.',
  denyPermanentDescription: 'This blocks future requests for this tool from this agent. You can revoke the decision from Approvals.',
  confirmPermanentDeny: 'Confirm permanent denial',
  scope: 'Approval scope',
  exactRequest: 'Exact request',
  customRule: 'Custom rule',
  thisValue: 'This value',
  anyValue: 'Any value',
  customMatch: 'Custom match',
  scopeInstructions: 'Future calls must match this tool and these values. Change only what can differ.',
  requestDetails: 'Request details',
  currentValue: 'Current value',
  empty: '(empty)',
  matches: 'matches',
  matchMode: (label: string) => `${label} match mode`,
  customMatchLabel: (label: string) => `${label} custom match`,
  customMatchDescription: 'Use * for any characters. Example: acme/* matches values that start with acme/.',
  showFullValue: 'Show full value',
  hideFullValue: 'Hide full value',
  resetScope: 'Reset to this request',
  appliesTo: 'Applies to',
  onlyTool: 'Only the tool',
  forAgent: (agent: string) => `for ${agent}`,
  anyValueSummary: (label: string) => `${label}: any value`,
  customValueSummary: (label: string) => `${label}: values matching`,
  exactValueSummary: (label: string) => `${label}: exactly`,
  changedParameter: (label: string, any: boolean) => `${label} (${any ? 'any value' : 'custom match'})`,
  changedScope: (changes: string[], total: number) => `Future calls may vary: ${changes.join(', ')}${total > changes.length ? `, +${total - changes.length} more` : ''}`,
  exactScope: (count: number) => count === 0 ? 'Future calls must match this tool.' : `Future calls must match this tool and all ${count} values from this request.`,
  technicalRule: 'Technical rule',
  validatingScope: 'The broker is validating this scope.',
  invalidScope: 'The broker could not validate this scope. Adjust the scope or try the preview again.',
  retryPreview: 'Try preview again',
  approved: 'Approved',
  denied: 'Denied',
  recorded: 'Decision recorded',
  readonly: 'This request is complete and is shown read-only.',
  closePage: 'You can safely close this page.',
  returnToAgent: 'You can return to your agent now.',
  nextInvocation: 'The next tool invocation will be allowed.',
  consumed: 'The approved tool invocation has already been used.',
  managePermanent: 'Manage this permanent decision from Approvals.',
  decisionContext: (tool: string, agent?: string) => agent ? `${tool} for ${agent}` : tool,
  decidedAt: (outcome: string, relativeTime: string) => `${outcome} ${relativeTime}`,
  persistenceValue: { once: 'once', session: 'session', permanent: 'permanent' },
  errors: {
    EXPIRED: { title: 'Approval expired', description: 'This approval request has timed out. The agent must submit a new request.', retryable: false },
    ALREADY_ACTIONED: { title: 'Already resolved', description: 'This approval already has a decision. No further action is available.', retryable: false },
    FORBIDDEN: { title: 'Access denied', description: 'You do not have permission to view or act on this approval.', retryable: false },
    NOT_FOUND: { title: 'Not found', description: 'This approval request does not exist or is no longer available.', retryable: false },
    NETWORK_ERROR: { title: 'Connection error', description: 'Unable to reach the server. Check your connection before you try again.', retryable: true },
    SERVER_ERROR: { title: 'Server error', description: 'The server could not complete the request. Try again later.', retryable: true },
    INVALID_PATTERN: { title: 'Scope not accepted', description: 'This scope does not cover the tool call. Adjust the scope and try again.', retryable: false },
  },
} as const;
