export const approvalQueueCopy = {
  purpose: 'Review pending tool requests and manage remembered decisions.',
  pendingTitle: 'Pending',
  rememberedTitle: 'Remembered',
  pendingEmpty: "You're all caught up",
  pendingEmptyDescription: 'Requests appear here when an agent needs your decision.',
  rememberedEmpty: 'No remembered decisions',
  rememberedEmptyDescription: 'Always allowed and always denied decisions appear here.',
  standingLoading: 'Loading remembered decisions.',
  pendingError: 'Pending approvals could not be loaded.',
  standingError: 'Remembered decisions could not be loaded.',
  standingStale: 'Remembered decisions may be out of date.',
  denyPermanently: 'Always deny…',
  allowed: 'Always allowed',
  denied: 'Always denied',
  revokeTitle: 'Revoke remembered decision?',
  revokeDescription: 'Remove the remembered decision for this tool and agent?',
  revokeEffect: 'Future matching requests will need a new decision.',
  confirmRevoke: 'Revoke decision',
  revoking: 'Revoking…',
  revokeSuccess: 'Remembered decision revoked.',
  revokeError: 'The remembered decision could not be revoked. It has not been removed.',
  all: 'All',
  filter: 'Filter decisions',
  searchRemembered: 'Search tools, agents, or patterns',
  viewPattern: 'View full scope pattern',
  expiresIn: (minutes: number) => `Expires in ${minutes} ${minutes === 1 ? 'minute' : 'minutes'}`,
  expiresSoon: (minutes: number) => `${minutes} min left`,
  selectedRequest: 'Selected request',
  back: 'Back',
  always: 'Always…',
  approveSession: 'Approve for this session',
  approveAlways: 'Always approve',
  denyAlways: 'Always deny',
  approveOptions: 'Approve options',
  denyOptions: 'Deny options',
  shortcutScope: 'Focus a request or its details to use shortcuts.',
  nextShortcut: 'J next',
  previousShortcut: 'K previous',
  focusShortcut: 'Enter details',
  approvedToast: 'Request approved.',
  deniedToast: 'Request denied.',
  viewJson: 'View JSON',
  rawArguments: 'Raw tool arguments',
  rawArgumentsDescription: 'The complete arguments supplied with this tool request.',
  noArguments: 'No arguments supplied.',
  arrivals: (count: number) => `${count} new approval ${count === 1 ? 'request' : 'requests'}.`,
  changed: (count: number) => `${count} approval ${count === 1 ? 'request updated' : 'requests updated'}.`,
  ageUnknown: 'Creation time unavailable',
  ageSeconds: 'Just now',
  ageMinutes: (count: number) => `${count} ${count === 1 ? 'minute' : 'minutes'} ago`,
  ageHours: (count: number) => `${count} ${count === 1 ? 'hour' : 'hours'} ago`,
  ageDays: (count: number) => `${count} ${count === 1 ? 'day' : 'days'} ago`,
} as const;
