export const approvalQueueCopy = {
  purpose: 'Review pending tool requests and manage remembered decisions.',
  pendingTitle: 'Pending requests',
  standingAllowTitle: 'Standing allow decisions',
  standingDenyTitle: 'Standing deny decisions',
  pendingEmpty: 'No pending approvals',
  pendingEmptyDescription: 'New tool requests will appear here when an agent needs your decision.',
  allowEmpty: 'No standing allow decisions',
  denyEmpty: 'No standing deny decisions',
  standingLoading: 'Loading standing decisions.',
  pendingError: 'Pending approvals could not be loaded.',
  standingError: 'Standing decisions could not be loaded.',
  standingStale: 'Standing decisions may be out of date.',
  tool: 'Tool',
  agent: 'Agent',
  risk: 'Risk',
  age: 'Age',
  actions: 'Actions',
  scope: 'Scope',
  decision: 'Decision',
  approve: 'Approve',
  confirmApprove: 'Confirm approve',
  denyOnce: 'Deny this request',
  denyPermanently: 'Always deny',
  denyDescription: 'Deny this request only, or remember a denial for this tool and its exact scope.',
  permanentDenyWarning: 'Future matching requests will be denied until you revoke this decision.',
  allowed: 'Permanently allowed',
  denied: 'Permanently denied',
  expired: 'This request has expired. No decision can be submitted.',
  revokeTitle: 'Revoke standing decision?',
  revokeDescription: (tool: string) => `Remove the remembered decision for ${tool}? Future matching requests will need a new decision.`,
  confirmRevoke: 'Revoke decision',
  revoking: 'Revoking…',
  revokeSuccess: 'Standing decision revoked.',
  revokeError: 'The standing decision could not be revoked. It has not been removed.',
  arrivals: (count: number) => `${count} new approval ${count === 1 ? 'request' : 'requests'}.`,
  changed: (count: number) => `${count} approval ${count === 1 ? 'request updated' : 'requests updated'}.`,
  ageUnknown: 'Creation time unavailable',
  ageSeconds: 'Just now',
  ageMinutes: (count: number) => `${count} ${count === 1 ? 'minute' : 'minutes'} ago`,
  ageHours: (count: number) => `${count} ${count === 1 ? 'hour' : 'hours'} ago`,
  ageDays: (count: number) => `${count} ${count === 1 ? 'day' : 'days'} ago`,
} as const;
