export const approvalCopy = {
  title: 'Tool Approval Request',
  description: 'Review the tool call and its scope before you decide.',
  requestedBy: 'Requested by',
  actingUser: 'Acting user',
  action: 'Action',
  technicalDetails: 'Technical details',
  arguments: 'Arguments',
  sessionContext: 'Session context',
  agentSession: 'Agent session',
  mcpSession: 'MCP session',
  toolInvocation: 'Tool invocation',
  covers: 'Covers',
  patternPreview: 'Approval pattern preview',
  expiry: (date: string) => `Expires: ${date}`,
  lowRisk: 'Low Risk',
  mediumRisk: 'Medium Risk',
  highRisk: 'High Risk',
  criticalRisk: 'Critical Risk',
  otherRisk: (level: string) => `${level} Risk`,
  riskExplanation: 'The server supplies this risk rating. A low rating does not guarantee that the tool call is safe.',
  unratedExplanation: 'The server did not supply a risk rating for this tool call.',
  persistence: 'Approval persistence',
  persistenceLegend: 'How long should this be allowed?',
  once: 'Just this once',
  onceDescription: 'Allow this tool call only. The agent must request approval again for the next call.',
  session: 'For this session',
  sessionDescription: 'Allow matching tool calls for the current session.',
  permanent: 'Always allow',
  permanentDescription: 'Allow matching tool calls from this agent until you revoke this decision.',
  warning: 'Warning:',
  permanentWarning: 'This grants permanent access. You can revoke it from Approvals.',
  rememberDescription: 'Choose a duration and review the scope. Only your confirmation records this approval.',
  confirmApproval: 'Confirm approval',
  denyPermanently: 'Deny permanently — block this tool for this agent',
  denyPermanentDescription: 'This blocks future requests for this tool from this agent. You can revoke the decision from Approvals.',
  confirmPermanentDeny: 'Confirm permanent denial',
  scope: 'Approval scope',
  exactRequest: 'Exact request',
  customRule: 'Custom rule',
  thisValue: 'This value',
  anyValue: 'Any value',
  customMatch: 'Custom match',
  scopeInstructions: 'Future calls must match this tool and these values. Change only what can differ.',
  requestDetails: 'Request details',
  currentValue: 'Current value',
  empty: '(empty)',
  matches: 'matches',
  matchMode: (label: string) => `${label} match mode`,
  customMatchLabel: (label: string) => `${label} custom match`,
  customMatchDescription: 'Use * for any characters. Example: acme/* matches values that start with acme/.',
  showFullValue: 'Show full value',
  hideFullValue: 'Hide full value',
  resetScope: 'Reset to this request',
  appliesTo: 'Applies to',
  onlyTool: (name: string) => `Only the tool ${name}`,
  anyValueSummary: (label: string) => `${label}: any value`,
  customValueSummary: (label: string, pattern: string) => `${label}: values matching ${pattern}`,
  exactValueSummary: (label: string, value: string) => `${label}: exactly ${value}`,
  changedParameter: (label: string, any: boolean) => `${label} (${any ? 'any value' : 'custom match'})`,
  changedScope: (changes: string[], total: number) => `Future calls may vary: ${changes.join(', ')}${total > changes.length ? `, +${total - changes.length} more` : ''}`,
  exactScope: (count: number) => count === 0 ? 'Future calls must match this tool.' : `Future calls must match this tool and all ${count} values from this request.`,
  technicalRule: 'Technical rule',
  validatingScope: 'The broker is validating this scope.',
  invalidScope: 'The broker could not validate this scope. Adjust the scope or try the preview again.',
  retryPreview: 'Try preview again',
  approved: 'Approved',
  denied: 'Denied',
  recorded: 'Decision recorded',
  readonly: 'This request is complete and is shown read-only.',
  closePage: 'You can safely close this page.',
  returnToAgent: 'You can return to your agent now.',
  nextInvocation: 'The next tool invocation will be allowed.',
  consumed: 'The approved tool invocation has already been used.',
  managePermanent: 'Manage this permanent decision from Approvals.',
  decisionContext: (tool: string, agent?: string) => agent ? `${tool} for ${agent}` : tool,
  decidedAt: (outcome: string, date: string) => `${outcome} at ${date}`,
  persistenceValue: { once: 'once', session: 'session', permanent: 'permanent' },
  errors: {
    EXPIRED: { title: 'Approval Expired', description: 'This approval request has timed out. The agent must submit a new request.', retryable: false },
    ALREADY_ACTIONED: { title: 'Already Resolved', description: 'This approval already has a decision. No further action is available.', retryable: false },
    FORBIDDEN: { title: 'Access Denied', description: 'You do not have permission to view or act on this approval.', retryable: false },
    NOT_FOUND: { title: 'Not Found', description: 'This approval request does not exist or is no longer available.', retryable: false },
    NETWORK_ERROR: { title: 'Connection Error', description: 'Unable to reach the server. Check your connection before you try again.', retryable: true },
    SERVER_ERROR: { title: 'Server Error', description: 'The server could not complete the request. Try again later.', retryable: true },
    INVALID_PATTERN: { title: 'Scope Not Accepted', description: 'This scope does not cover the tool call. Adjust the scope and try again.', retryable: false },
  },
} as const;
