export const connectionsCopy = {
  scopes: 'Granted scopes',
  scopeCount: (count: number) => `${count} ${count === 1 ? 'scope' : 'scopes'}`,
  connectedDate: 'Connected',
  emptyTitle: 'No connections yet',
  empty: 'You connect a service when an agent asks for access to it.',
  readError: 'Your connections could not load. Try again.',
  stale: 'Connection details may be out of date.',
  unavailable: 'Unavailable',
  expiredExplanation: 'Your access expired. Reconnect to continue.',
  refreshExplanation: 'Your access expired. Refresh to continue.',
  reauthenticationExplanation: 'Sign in again to continue.',
  unavailableExplanation: 'Connection details are unavailable. Try again.',
  refreshSuccess: 'Connection refreshed.',
  refreshError: 'Could not refresh this connection. Please try again.',
  activeFilters: 'Active connection filters',
  sortAttention: 'Needs attention first',
  sortRecentlyConnected: 'Recently connected',
  filterConnected: 'Connected',
  filterNeedsSignIn: 'Needs sign-in',
  filterExpired: 'Expired',
  filterUnavailable: 'Unavailable',
  removeSearch: 'Remove search',
  removeFilter: 'Remove state filter',
  removeSort: 'Reset sort',
  disconnectTitle: 'Disconnect service',
  disconnectDescription: (provider: string) => `Disconnect ${provider} from this broker?`,
  providerWarning: 'Disconnecting from this broker does not revoke provider-side tokens. You can revoke those tokens in the provider settings.',
  dependentAgents: 'These agents lose access through this connection:',
  noDependentAgents: 'No agents depend on this connection.',
  detailsError: 'Could not load connection details. Please try again.',
  disconnectSuccess: 'Connection disconnected.',
  disconnectError: 'Could not disconnect this connection. Please try again.',
  callbackSuccess: 'Service connected. Your agents can now request access.',
  callbackFailure: 'Authorization failed. Please try again.',
} as const;

export function connectionCallbackError(code: string): string {
  const messages: Record<string, string> = {
    access_denied: 'You denied access to the service. No tokens were stored.',
    invalid_scope: 'The requested permissions are not available. Please contact support.',
    expired_token: 'Your authorization expired. Please try again.',
    callback_failed: connectionsCopy.callbackFailure,
    invalid_callback: 'Invalid response from service. Please try again.',
    invalid_state: 'Invalid request state. Please try again.',
    invalid_redirect_uri: 'Invalid redirect configuration. Please contact support.',
  };
  return Object.prototype.hasOwnProperty.call(messages, code) ? messages[code] : connectionsCopy.callbackFailure;
}
