export const consentCopy = {
  ableTo: 'It will be able to',
  accessLasts: 'Access lasts',
  chooseServices: (group: string) => `Choose services for ${group}`,
  servicesFor: (group: string) => `Services for ${group}`,
  selectedServices: (selected: number, total: number) => `${selected} of ${total} services`,
  morePermissions: (count: number) => `${count} more`,
  more: 'More',
  less: 'Less',
  granted: 'Granted',
  missingConnection: (service: string) => `${service} needs a connection`,
  connect: 'Connect',
  connectService: (service: string) => `Connect ${service}`,
  reconnectService: (service: string) => `Reconnect ${service}`,
  connectToContinue: (service: string) => `Connect ${service} to continue`,
  chooseCustomDate: 'Choose custom date',
  untilRevoked: 'Until I revoke it',
  headingSuffix: 'wants to act on your behalf',
  about: 'About this agent',
  technicalDetails: 'Technical details',
  agentId: 'Agent ID',
  clientUris: 'Registered client URIs',
  grantId: 'Grant ID',
  grantCreated: 'Grant created',
  grantUpdated: 'Grant updated',
  signedInAs: (name: string) => `Signed in as ${name}`,
  redirectHost: (host: string) => `Returns to ${host}`,
  unverifiedWarning: 'This agent’s origin is unverified. Continue only if you trust this request.',
  unverifiedLocalWarning: (agent: string) => `This agent’s origin is unverified and this request returns to your own computer. Continue only if you started it from ${agent}.`,
  reassurance: 'You can change or revoke this at any time in',
  validationSummary: 'Review the highlighted selection before allowing access.',
  deniedTitle: 'Access denied. Nothing was changed.',
  closeTab: 'You can close this tab.',
  allowedTitle: 'Access allowed.',
  connectionWarning: (agent: string) => `This request returns to your own computer. Continue only if you started it from ${agent}.`,
  governance: 'Governance',
  documentation: 'Documentation',
  agentInterface: 'Agent interface',
  required: 'Required',
  services: 'Services',
  noPermissions: 'This agent does not request permission groups.',
  clientId: 'Client ID',
  redirectUri: 'Redirect URI',
  requestedScopes: 'Requested scopes',
  noneRequested: 'None requested',
  invalidDate: 'Choose a date after today.',
  selectPermission: 'Select at least one permission group.',
  selectService: 'Select at least one service in each permission group.',
  connectionStorageError: 'Cannot save your choices in this tab. Enable browser storage and try connecting again.',
  invalidSession: 'This authorization session is invalid or expired, so start a new request from the agent.',
  loadError: 'Could not load this agent. Try again.',
  saveError: 'Could not save your changes. Your access has not changed.',
  invalidRedirect: 'Invalid redirect URL. Return to the agent to continue.',
  grantSaved: 'Grant updated successfully.',
  grantRevoked: 'All access for this agent has been revoked.',
  grantRevokeError: 'Could not revoke access. Try again.',
  actions: 'Agent actions',
  unsavedChanges: 'Unsaved changes',
  saveBeforeLeaving: 'Save your changes before leaving this page.',
  discardTitle: 'Discard unsaved changes?',
  discardDescription: 'Your permission and access-duration edits have not been saved.',
  keepEditing: 'Keep editing',
  discardChanges: 'Discard changes',
  currentExpiry: 'Current access',
  pendingExpiry: 'After saving',
  expiryOn: (date: string) => `Until ${date}`,
  expiryPending: 'Choose a valid date to preview the new expiry.',
  manageConnections: 'Manage connection',
  manage: 'Manage',
  noConnections: 'This agent does not require a service connection.',
  connectionsLoadError: 'Could not load connection details. Try again.',
  connectedExplanation: 'This service is connected.',
  noConnectionExplanation: 'No connection yet. Connect this service before using it with this agent.',
  checkConnections: 'Open Connections to check the latest status.',
} as const;
