export const consentCopy = {
  permissions: 'Permissions',
  accessDuration: 'Access duration',
  requestSummary: (agent: string) => `${agent} requests permission to use the services you select below.`,
  governance: 'Governance',
  documentation: 'Documentation',
  agentInterface: 'Agent interface',
  expandAgentName: 'Show full agent name',
  collapseAgentName: 'Collapse agent name',
  expandDescription: 'Show full description',
  collapseDescription: 'Collapse description',
  expandGroupName: 'Show full permission name',
  collapseGroupName: 'Collapse permission name',
  required: 'Required',
  optional: 'Optional',
  alreadyGranted: 'Already granted',
  services: 'Services',
  noPermissions: 'This agent does not request permission groups.',
  localhostWarning: (agent: string) => `This app is requesting a redirect to your local machine. Make sure you started this request from ${agent}.`,
  advancedDetails: 'Advanced details',
  clientId: 'Client ID',
  redirectUri: 'Redirect URI',
  requestedScopes: 'Requested scopes',
  noneRequested: 'None requested',
  invalidDate: 'Choose a date after today.',
  selectPermission: 'Select at least one permission group.',
  selectService: 'Select at least one service in each permission group.',
  connectFirst: 'Connect the selected services before you allow access.',
  connectionStorageError: 'Cannot save your choices in this tab. Enable browser storage and try connecting again.',
  nextSteps: 'After you allow access, the agent can use your selected services. Review or revoke access at /delegations.',
  denied: 'Access denied. No access was added or revoked. You can close this page.',
  allowed: 'Access allowed. You can manage or revoke access at /delegations.',
  invalidSession: 'Your authorization session is invalid or expired. Return to the agent and start a new authorization request.',
  loadError: 'Could not load this agent. Try again.',
  saveError: 'Could not save your changes. Your access has not changed.',
  invalidRedirect: 'Invalid redirect URL. Return to the agent to continue.',
  grantSaved: 'Grant updated successfully.',
  grantRevoked: 'All access for this agent has been revoked.',
  grantRevokeError: 'Could not revoke access. Try again.',
  actions: 'Agent actions',
  unsavedChanges: 'Unsaved changes',
  manageConnections: 'Manage connection',
  noConnections: 'This agent does not require a service connection.',
  connectionsLoadError: 'Could not load connection details. Try again.',
} as const;
