export const delegationsCopy = {
  purpose: 'Review and revoke the access you have delegated to agents.',
  emptyTitle: 'No agents yet',
  searchAgents: 'Search agents',
  expires: 'Expires',
  expiresSoon: 'Expires soon',
  changed: 'Changed',
  accessUntil: 'Access until',
  permissions: 'Permissions',
  back: 'Back to Agents',
  about: 'About',
  details: 'Agent details',
  detailStale: 'Agent details may be out of date. Try again to refresh.',
  revokeAccess: 'Revoke access',
  revokeSuccess: 'Access revoked.',
  revokeFailure: 'Could not revoke access. Try again.',
  loadFailure: 'Could not load agents.',
  stale: 'The agent list may be out of date.',
} as const;
